### ISSUE TITLE
项目结构过于复杂

### ISSUE THREAD

**Issue by wohelu666** [xiaojinzi123/TallyApp#2]
项目结构有点过于复杂了吧，建议如果是要开源的话，可以弄简单的一点，毕竟不是每个人的业务都需要这样来分开使用，更多还是一个叫交流学习的目的。

**Comment by xiaojinzi123** [comment]
那是因为我还没时间帮你们写一下架构图. 之后会补上的. 
结构其实不复杂. 而且这就是一个线上的项目, 我不是为了开源而开源. 我只是单纯的先让大家看一下在我的理解下. 
MVVM 响应式 + Compose + 组件化 是怎么样的.

**Comment by wohelu666** [comment]
好的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaojinzi123/TallyApp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaojinzi123/TallyApp] 项目结构过于复杂 (Issue #2)





 
那是因为我还没时间帮你们写一下架构图. 之后会补上的.
 结构其实不复杂. 而且这就是一个线上的项目, 我不是为了开源而开源. 我只是单纯的先让大家看一下在我的理解下.
 MVVM 响应式 + Compose + 组件化 是怎么样的.
