### ISSUE TITLE
我改为自己的giteetoken后编译出来，上传图片总是失败

### ISSUE THREAD

**Issue by jangufo** [xiaojinzi123/TallyApp#6]
难道需要在gitee哪里配置什么吗？我gitee上给了全部权限了，真的只需要一个token吗，难道不用建仓库什么的？我不会搞了，需要配什么求大佬告诉我一下

**Comment by xiaojinzi123** [comment]
1. 配置选择国内的, 图片才会走 gitee
![image](https://github.com/xiaojinzi123/TallyApp/assets/12975743/3e8008d0-d446-4b82-92d6-4ef9de28f265)
2. gitee 的 token 配置
3. 更换账号和仓库为你自己的
![image](https://github.com/xiaojinzi123/TallyApp/assets/12975743/535bce2b-3725-4a72-9744-1050c29710a9)

**Comment by jangufo** [comment]
感谢大佬，终于编译成功了
